'use strict';
import { StyleSheet, } from 'react-native';
let Dimensions = require('Dimensions');
let { width, height } = Dimensions.get('window');
import color from '../../constant/color';
const styles = StyleSheet.create({
  main: {
    flex: 1,
    flexDirection:'column',
    alignItems: 'center',
    width:width,
    height:height,
    backgroundColor:color.mainBg2C,
  },
  afterService:{
    width:54,
    height:20,
    borderColor:color.main1C,
    borderWidth:1,
    justifyContent:"center",
    alignItems:"center",
  },
  afterText:{
    fontSize:13,
    color:color.main1C,
  },
  tel_box:{
    justifyContent:"center",
    width:width,
    height:46,
    borderTopWidth:1,
    borderColor:"#dedbd7",
    flexDirection:"row",
    alignItems:"center"
  },
  freightText_l:{
    fontSize:14,
    color:"#303030",
  },
  freightText_r:{
    fontSize:12,
    color:color.font1C,
  },
  payText_l:{
    fontSize:15,
    color:"#303030",
  },
  payText_r:{
    fontSize:15,
    color:color.main1C,
  },
  telBussText:{
    fontSize:13,
    color:"#5794d7",
    paddingLeft:5,
  },
  date_box:{
    width:width-30,
  },
  tel_btn:{
    width:16,
    height:16,
  },
  dateText:{
    fontSize:12,
    lineHeight:20,
    color:color.font1C,
  },
  orderRow:{
    width:width,
    borderColor:color.line1C,
    borderTopWidth:1,
    justifyContent:'center',
    alignItems:'center',
  },
  finsh_text:{
    lineHeight:18,
    fontSize:12,
    color:color.font2C,
  },
  label_box:{
    width:width,
    alignItems:"center",
    backgroundColor:color.back1C,
    marginTop:10,
    borderBottomWidth:1,
    borderColor:"#eae8e3",
  },
  labels:{
    width:width-30,
    flexDirection:"row",
  },
  textGenneral:{
    fontSize:12,
    color:color.font2C,
  },
  listLeft:{
    width:71,
    height:71,
    borderWidth:1,
    borderColor:color.line1C,
    alignItems:"center",
    justifyContent:"center"
  },
  return_img:{
    width:46,
    height:61,
  },
  listRight:{
    height:70,
    paddingLeft:10,
    width:width-30-71,
  },
  name_text:{
    fontSize:15,
    color:color.back3C,
  },
  goods_info:{
    flexDirection:"row",
    alignItems:"center",
    justifyContent:"space-between",
  },
  textPrice:{
    fontSize:15,
    color:color.main1C,
  },
  footRight:{
    position:"relative",
    width:65,
    height:23,
    alignItems:"center",
    justifyContent:"center",
  },
  yes_btn:{
    position:"absolute",
    width:65,
    height:23,
  },
  f_text:{
    fontSize:12,
    color:color.font2C,
  },
  yes_text:{
    fontSize:14,
    color:color.main1C,
  },
  giveState:{
    flexDirection:'row',
    justifyContent:"flex-start",
    alignItems:"flex-start",
    height:32,
  },
  Distribution_icon:{
    width:12,
    height:9,
    marginTop:7,
  },
  headText:{
    fontSize:13,
    color:color.font1C,
  },
  giveInfo:{
    height:44,
    justifyContent:"space-around",
    paddingLeft:10,
  },

  r_head_t:{
    height:30,
    width:width-30-20,
    flexDirection:"row",
    justifyContent:"space-between",
    alignItems:"center",

  },
  adress_info_box:{
    paddingBottom:6,
    width:width-30-20,
    justifyContent:"center"
  },
  adress_icon:{
    width:12,
    height:12,
    marginTop:38,
  }
})

export default styles;
