'use strict';
import { StyleSheet, } from 'react-native';
import Dimensions from 'Dimensions';
let { width, height } = Dimensions.get('window');
import color from '../../constant/color';
const styles = StyleSheet.create({
  main: {
    flex: 1,
    flexDirection:'column',
    alignItems:'center',
    width:width,
    height:height,
    backgroundColor:color.mainBg2C,
  },
  footRight:{
    position:"relative",
    width:65,
    height:23,
    alignItems:"center",
    justifyContent:"center",
  },
  yes_btn:{
    position:"absolute",
    top:0,
    width:65,
    height:23,
  },
  yes_text:{
    fontSize:14,
    color:color.main1C,
  },
  PickerBox:{
    flex:1,
    borderColor:"#d5d6d7",
    borderWidth:0.5,
    height:30,
    padding:0,
  },
  seviceText:{
    fontSize:15,
    color:"#303030",
  },
  seviceInfo:{
    width:width,
    alignItems:"center",
    justifyContent:"center",
    borderBottomWidth:1,
    borderColor:"#dedbd7",
    backgroundColor:color.back1C,
  },

  reason_box:{
    width:width,
    paddingTop:7,
    height:133,
    alignItems:"center",
    borderBottomWidth:1,
    borderColor:"#dedbd7",
    backgroundColor:color.back1C,
  },
  sevice:{
    width:width-30,
    flexDirection:"row",
    height:48.5,
    justifyContent:"center",
    alignItems:"center",
  },
  reTextBox:{
    width:width-30,
    height:31,
    justifyContent:"center",
  },
  f_Box:{
    flex:1,
    alignItems:"center",
  },
  fileBox:{
    width:width-30,
    alignItems:"flex-start",
  },
  fileBtn:{
    width:75,
    height:75,
    marginTop:15,
    borderWidth:0.5,
    borderStyle:"dashed",
    borderColor:"#c6c3bf",
    alignItems:"center",
  },
  fileIcon:{
    width:15,
    height:15,
    marginTop:18.5,
    marginBottom:4,
  },
  file_text:{
    fontSize:12,
    color:color.font1C,
  },
  return_bg:{
    width:140,
    height:145,
    marginTop:14,
  },
  footer:{
    width:width,
    height:45,
    borderTopWidth:1,
    backgroundColor:color.back1C,
    borderColor:"#dedbd7",
    alignItems:"center",
    justifyContent:"center",
  },
})
module.exports= styles;
